analytics:
  disable: true

communications:
  'default-group':
    slack: # Configuration for the Slack app with RTM support
      enabled: false # Tests will override this temporarily
      token: "" # Provide a valid token for Botkube app
      channels:
        'default':
          name: "" # Tests will override this temporarily
          bindings:
            executors:
              - kubectl-read-only
              - kubectl-wait-cmd
              - kubectl-exec-cmd
              - kubectl-allow-all
              - plugin-based
            sources:
              - k8s-events
              - k8s-pod-create-events
        'secondary':
          name: "" # Tests will override this temporarily
          notification:
            disabled: true
          bindings:
            executors:
              - kubectl-read-only
            sources:
              - k8s-updates
    discord:
      enabled: false # Tests will override this temporarily
      token: "" # Provide a valid token for Botkube app
      botID: "" # Provide a valid Application Client ID for Botkube app
      channels:
        'default':
          id: "" # Tests will override this channel ID temporarily
          bindings:
            executors:
              - kubectl-read-only
              - kubectl-wait-cmd
              - kubectl-exec-cmd
              - kubectl-allow-all
            sources:
              - k8s-events
              - k8s-pod-create-events
        'secondary':
          id: "" # Tests will override this channel ID temporarily
          notification:
            disabled: true
          bindings:
            # -- Executors configuration for a given channel.
            executors:
              - kubectl-read-only
            # -- Notification sources configuration for a given channel.
            sources:
              - k8s-updates

sources:
  'k8s-events':
    kubernetes:
      recommendations:
        pod:
          noLatestImageTag: true
          labelsSet: true
        ingress:
          backendServiceValid: false
          tlsSecretValid: false
      namespaces:
        include:
          - botkube
      events:
        - create
        - update
        - delete
      resources:
        - name: v1/configmaps
  'k8s-pod-create-events':
    kubernetes:
      namespaces:
        include:
          - botkube
      events:
        - create
      resources:
        - name: v1/pods

  'k8s-updates':
    kubernetes:
      namespaces:
        include:
          - default
      events:
        - create
        - update
        - delete
      resources:
        - name: v1/configmaps
          namespaces:
            include:
              - botkube
          events: # overrides top level `events` entry
            - update
executors:
  'kubectl-read-only':
    kubectl:
      enabled: true
      namespaces:
        include:
          - botkube
          - default
  'kubectl-wait-cmd':
    kubectl:
      enabled: true
      namespaces:
        include:
          - botkube
          - default
      commands:
        verbs: [ "wait" ]
      restrictAccess: false
  'kubectl-exec-cmd':
    kubectl:
      enabled: false
      namespaces:
        include:
          - botkube
          - default
      commands:
        verbs: [ "exec" ]
      restrictAccess: false
  'kubectl-allow-all':
    kubectl:
      enabled: true
      namespaces:
        include:
          - ".*"
      commands:
        verbs: [ "get" ]
        resources: [ "deployments" ]
  'kubectl-not-bound-to-any-channel':
    kubectl:
      enabled: true
      namespaces:
        include:
          - ".*"
      commands:
        verbs: [ "port-forward" ]
        resources: [ "deployments" ]

  'plugin-based': # FIXME: this should be generic? how we know which executors are enabled? what about settings?
    botkube/echo: # <repo>/<plugin_name> is syntax for plugin based executors
      enabled: true
      config:
        changeResponseToUpperCase: true

plugins:
  cacheDir: "/tmp"
  repositories:
    botkube: http://host.k3d.internal:3000/botkube.yaml

actions:
  'get-created-resource':
    enabled: true
    displayName: "Get created resource"
    command: "kubectl get {{ .Event.TypeMeta.Kind | lower }}{{ if .Event.Namespace }} -n {{ .Event.Namespace }}{{ end }} {{ .Event.Name }}"
    bindings:
      sources:
        - k8s-pod-create-events
      executors:
        - kubectl-read-only

filters:
  kubernetes:
    objectAnnotationChecker: true
    nodeEventsChecker: false

settings:
  clusterName: sample
  upgradeNotifier: false
  persistentConfig:
    runtime:
      configMap:
        annotations:
          botkube.io/disable: "true"
    startup:
      configMap:
        annotations:
          botkube.io/disable: "true"

extraAnnotations:
  botkube.io/disable: "true"
