name: Code freeze

on:
  workflow_dispatch:
    inputs:
      from:
        type: string
        description: Branch, commit, or commit SHA
        required: true
        default: main
      version:
        type: string
        description: Version of the next release
        required: true

env:
  git-user: github-actions[bot]
  git-email: 41898282+github-actions[bot]@users.noreply.github.com

permissions:
  contents: write
  pages: write
  pull-requests: write
  packages: write

jobs:
  code-freeze:
    name: Create release/${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.from }}
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set git 'user.name' and 'user.email'
        run: |
          git config user.name "${{ env.git-user }}"
          git config user.email ${{ env.git-email }}

      - name: Create a release branch
        run: |
          git checkout -b release/${{ inputs.version }}

      - name : Push new branch
        run: git push origin release/${{ inputs.version }}

      - name: Add note for previous version
        run: |
          git fetch --all
          PREV_VERSION=${{ inputs.from }}
          if git show-ref --quiet "refs/heads/${{ inputs.from }}"; then
            echo "${{ inputs.from }} is a branch, will find latest tag..."
            PREV_VERSION=$(git for-each-ref --sort=-creatordate --format '%(refname)' refs/tags | grep -E "\.0$" | awk -F'refs/tags/' '{ print $2 }'| head -1)
            echo "The latest tag on ${{ inputs.from }} is ${PREV_VERSION}"
          fi
          git notes --ref release/${{ inputs.version }} add -m "previous-version: ${PREV_VERSION}"
          git push origin 'refs/notes/*'
